version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - keycloak_data:/opt/keycloak/data


  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"


  # postgres:
  #   image: postgres:15
  #   container_name: postgres
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: user_db
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  keycloak_data:
  # postgres_data:

